services:
  jupyterhub:
    build: .
    ports:
      - "8000:8000"
    environment:
      JUPYTERHUB_ADMIN: ${JUPYTERHUB_ADMIN}
      JUPYTERHUB_ADMIN_PASSWORD: ${JUPYTERHUB_ADMIN_PASSWORD}
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
